services:
  - type: web
    name: diecast-api
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/diecast-api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false