# Nama app
spring.application.name=diecast-api

# Koneksi database — ambil dari Supabase lo
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Jangan ubah/hapus tabel yang udah ada
spring.jpa.hibernate.ddl-auto=validate

# Biar keliatan query SQL yang dijalankan di terminal (optional, bagus buat belajar)
spring.jpa.show-sql=true

# Port default 8080, bisa diganti kalau bentrok
server.port=8080