# Nama app
spring.application.name=DiecastData API

# Koneksi database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Port
server.port=${PORT:8080}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.info.title=DiecastData API
springdoc.info.description=Backend API untuk manajemen inventory dan keuangan diecast/Hot Wheels
springdoc.info.version=1.0.0
