# Nama app
spring.application.name=diecast-api

# Koneksi database — ambil dari Supabase lo
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Jangan ubah/hapus tabel yang udah ada
spring.jpa.hibernate.ddl-auto=validate

# Biar keliatan query SQL yang dijalankan di terminal (optional, bagus buat belajar)
spring.jpa.show-sql=true

# Port default 8080, bisa diganti kalau bentrok
server.port=${8080}

# swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.application.name=DiecastData API
springdoc.info.title=DiecastData API
springdoc.info.description=Backend API untuk manajemen inventory dan keuangan diecast/Hot Wheels
springdoc.info.version=1.0.0